# Generated by Django 5.0.4 on 2024-05-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0001_initial'),
        ('patients', '0003_patient_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
