# Generated by Django 5.0.4 on 2024-05-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0002_alter_medicalhistory_patient_id'),
        ('patients', '0005_remove_patient_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
